
name: iac-dre-workflow
concurrency: iac-dre-workflow

on:
  push:
    branches:
      - main
    paths:
      - 'bicep/products/rayobeam/**'
      - '.github/workflows/iac-dre-workflow.yml'
      - '.github/workflows/iac-ci-template.yml'
      - '.github/workflows/iac-cd-template.yml'
  
  workflow_dispatch:
    
permissions:
  contents: read
  id-token: write


jobs:
  build:
    uses: ./.github/workflows/iac-ci-template.yml
    with:
      environment: de
      location: canadacentral
      project: rayobeam
      projectFolder: rayobeam
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  get-group-id:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Group ID
      id: get-group-id
      run: |
        GROUP_ID=$(az ad group show --group "YourGroupName" --query objectId --output tsv)
        echo "GROUP_ID=$GROUP_ID" >> $GITHUB_ENV

  deploy-de:
    uses: ./.github/workflows/iac-cd-template.yml
    needs: build
    with:
      environment: de
      location: canadacentral
      project: rayobeam
      projectFolder: rayobeam
      groupSid: ${{ env.GROUP_ID }}
      rbac: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}